language: java
sudo: required
dist: trusty
before_install:
  - export JAVA_VER=$(java -version 2>&1 | sed 's/java version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')
  - echo ${JAVA_VER}
  - sudo chmod a+x travis/pre_build.sh
  - ./travis/pre_build.sh
  - if [[ ${JAVA_VER} == "18" ]]; then jdk_switcher use oraclejdk8; fi
  - if [[ ${JAVA_VER} == "18" ]]; then export JAVA_HOME=/usr/lib/jvm/java-8-oracle; fi
  - echo ${JAVA_HOME}
  - java -version
  - javac -version
  - javah -version

install: GRADLE_OPTS="-XX:MaxPermSize=512m" gradle -q assemble
script: GRADLE_OPTS="-XX:MaxPermSize=512m" gradle -i check
jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

env:
  global:
    - secure: "NTxp50e11DMSJH1ApQbjlBxY4bcsLAGSw3mYzodOlceybMBh+hbpiAmqBpCZ9878wm5AZcPVq6ULzB47IrdfQG3Xn3SybwWLWpZRI3B0eaqoyhk71J5Uuu9rr+xXoD1C1q/TV1Z0Zf5unR1jz5DmUZ5En8yf4lZ4MI7gft6tDFI="
    - TERM=dumb
    - DOCS_BRANCH="0.7.0"
    - GEN_APIDOCS="gradle javadoc"

after_success:
  - sudo chmod a+x travis/post_build.sh
  - ./travis/post_build.sh

notifications:
  slack: puniverse:OsnbakHrYeTcLyalVgtUeI4F
